
apiVersion: batch/v1
kind: Job
metadata:
  name: ht-e-r-gd-1-gs-0-vm-0
  namespace: ucsd-haosulab
  labels:
    user: haotang # Specify your name
spec:
  ttlSecondsAfterFinished: 86400  # Wait one day to delete completed jobs
  template:
    spec:

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: nautilus.io/group
                  operator: In
                  values:
                  - haosu

      tolerations:
      - effect: NoSchedule
        key: nautilus.io/haosu
        operator: Exists
      - effect: NoSchedule
        key: nautilus.io/suncave
        operator: Exists
      tolerations:
      - effect: NoSchedule
        key: nautilus.io/wave
        operator: Exists
      containers:
      - name: gpu-container
        image: silent56/main:run3.sh
        command:
        - "sh"
        args:
        - "-c"
        - "cd /cephfs/haotang/PropNet && bash parallel.sh 'python train.py --env Rope --gen_data 1 --gen_stat 0 --verbose_model 0'"
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
            nvidia.com/gpu: 1
          limits:
            cpu: "3"
            memory: "10Gi"
            nvidia.com/gpu: 1
        volumeMounts:
          - name: cephfs-vol
            mountPath: /cephfs-old
          - name: cephfs
            mountPath: /cephfs
          # - name: dshm
            # mountPath: /dev/shm
      volumes:
      # - name: dshm  # shared memory
        # emptyDir:
          # medium: Memory
      - name: cephfs
        persistentVolumeClaim:
            claimName: haosulab-cephfs
      - name: cephfs-vol  # shared filesystem
        flexVolume:
          driver: ceph.rook.io/rook
          fsType: ceph
          options:
            fsName: nautilusfs
            clusterNamespace: rook
            path: /ucsd-haosulab
            mountUser: ucsd-haosulab
            mountSecret: ceph-fs-secret
      restartPolicy: Never
  backoffLimit: 2
    